In [105]:
import pandas as pd 
import numpy as np 
import seaborn as sb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import PCA
import warnings
warnings.filterwarnings('ignore')
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

In [106]:
data=pd.read_csv('sonar.csv',names=range(0,61),header=0)
data.head()

0       1       2       3       4       5       6       7       8   \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

       9   ...      51      52      53      54      55      56      57  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   

       58      59  60  
0  0.0052  0.0044   R  
1  0.0095  0.0078   R  
2  0.0040  0.0117   R  
3  0.0107  0.0094   R  
4  0.0051  0.0062   R  

[5 rows x 61 columns]

In [107]:
data=pd.DataFrame(data=data)

In [108]:
x=data.iloc[:,0:-1]

In [109]:
pca=PCA(n_components=10)
xpca=pca.fit_transform(x)

In [110]:
x=xpca

In [111]:
x=pd.DataFrame(data=x)

In [112]:
y=data.iloc[:,-1]

In [113]:
x.skew()

0    0.182486
1    0.412060
2    0.182902
3    0.438051
4   -0.057592
5    0.283933
6    0.415527
7    0.060027
8    0.226722
9   -0.297189
dtype: float64

In [114]:
x[9]=np.cbrt(x[9])

In [115]:
x.skew()

0    0.182486
1    0.412060
2    0.182902
3    0.438051
4   -0.057592
5    0.283933
6    0.415527
7    0.060027
8    0.226722
9   -0.055009
dtype: float64

In [116]:
le=LabelEncoder()
y=le.fit_transform(y)

In [117]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [118]:
scale=StandardScaler()
x=scale.fit_transform(x)

In [119]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.22,random_state=45)

In [120]:
lg=LogisticRegression()
lg.fit(x_train,y_train)
lg.score(x_train,y_train)
predlg=lg.predict(x_test)
print(accuracy_score(y_test,predlg))
print(confusion_matrix(y_test,predlg))
print(classification_report(y_test,predlg))

0.8043478260869565
[[23  1]
 [ 8 14]]
              precision    recall  f1-score   support

           0       0.74      0.96      0.84        24
           1       0.93      0.64      0.76        22

    accuracy                           0.80        46
   macro avg       0.84      0.80      0.80        46
weighted avg       0.83      0.80      0.80        46



In [121]:
gnb=GaussianNB()
svc=SVC()
dtc=DecisionTreeClassifier()


In [122]:
svc=SVC()
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=svc.predict(x_test)
print(accuracy_score(y_test,predsvc))
print(confusion_matrix(y_test,predsvc))
print(classification_report(y_test,predsvc))

0.8260869565217391
[[23  1]
 [ 7 15]]
              precision    recall  f1-score   support

           0       0.77      0.96      0.85        24
           1       0.94      0.68      0.79        22

    accuracy                           0.83        46
   macro avg       0.85      0.82      0.82        46
weighted avg       0.85      0.83      0.82        46



In [123]:
svc=SVC(kernel='poly')
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=svc.predict(x_test)
print(accuracy_score(y_test,predsvc))
print(confusion_matrix(y_test,predsvc))
print(classification_report(y_test,predsvc))

0.8260869565217391
[[24  0]
 [ 8 14]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86        24
           1       1.00      0.64      0.78        22

    accuracy                           0.83        46
   macro avg       0.88      0.82      0.82        46
weighted avg       0.87      0.83      0.82        46



In [124]:
dtc=DecisionTreeClassifier(criterion='gini')
dtc.fit(x_train,y_train)
dtc.score(x_train,y_train)
preddtc=dtc.predict(x_test)
print(accuracy_score(y_test,preddtc))
print(confusion_matrix(y_test,preddtc))
print(classification_report(y_test,preddtc))

0.6739130434782609
[[17  7]
 [ 8 14]]
              precision    recall  f1-score   support

           0       0.68      0.71      0.69        24
           1       0.67      0.64      0.65        22

    accuracy                           0.67        46
   macro avg       0.67      0.67      0.67        46
weighted avg       0.67      0.67      0.67        46



In [125]:
dtc=DecisionTreeClassifier(criterion='gini')
score=cross_val_score(dtc,x_train,y_train,cv=30,scoring='roc_auc')
print(score)
print(score.mean())

[0.5        0.66666667 0.83333333 1.         0.83333333 0.66666667
 0.66666667 0.5        0.83333333 1.         1.         0.83333333
 1.         0.66666667 1.         0.75       0.66666667 0.66666667
 1.         0.5        0.41666667 0.83333333 0.75       0.83333333
 0.41666667 1.         0.75       0.25       0.75       0.75      ]
0.7444444444444444


In [126]:
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)
knn.score(x_train,y_train)
predknn=knn.predict(x_test)
print(accuracy_score(y_test,predknn))
print(confusion_matrix(y_test,predknn))
print(classification_report(y_test,predknn))

0.8478260869565217
[[22  2]
 [ 5 17]]
              precision    recall  f1-score   support

           0       0.81      0.92      0.86        24
           1       0.89      0.77      0.83        22

    accuracy                           0.85        46
   macro avg       0.85      0.84      0.85        46
weighted avg       0.85      0.85      0.85        46



In [127]:
knn=KNeighborsClassifier(n_neighbors=3)
score=cross_val_score(knn,x_train,y_train,cv=4)
print(score)
print(score.mean())

[0.68292683 0.82926829 0.75       0.76923077]
0.7578564727954972


In [140]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=130,random_state=45,max_depth=8)
rfc.fit(x_train,y_train)
predrfc=rfc.predict(x_test)
print('Accuracy score is\n :',accuracy_score(y_test,predrfc))
print('\nConfusion matirx is :\n',confusion_matrix(y_test,predrfc))
print('\nClassification report is :',classification_report(y_test,predrfc))




Accuracy score is
 : 0.8478260869565217

Confusion matirx is :
 [[23  1]
 [ 6 16]]

Classification report is :               precision    recall  f1-score   support

           0       0.79      0.96      0.87        24
           1       0.94      0.73      0.82        22

    accuracy                           0.85        46
   macro avg       0.87      0.84      0.84        46
weighted avg       0.86      0.85      0.85        46



In [150]:
from sklearn.ensemble import GradientBoostingClassifier
abc=GradientBoostingClassifier(n_estimators=123,random_state=45,learning_rate=0.1,max_depth=2)
abc.fit(x_train,y_train)
predabc=abc.predict(x_test)
print('Accuracy score is\n :',accuracy_score(y_test,predabc))
print('\nConfusion matirx is :\n',confusion_matrix(y_test,predabc))
print('\nClassification report is :',classification_report(y_test,predabc))



Accuracy score is
 : 0.8695652173913043

Confusion matirx is :
 [[24  0]
 [ 6 16]]

Classification report is :               precision    recall  f1-score   support

           0       0.80      1.00      0.89        24
           1       1.00      0.73      0.84        22

    accuracy                           0.87        46
   macro avg       0.90      0.86      0.87        46
weighted avg       0.90      0.87      0.87        46



In [152]:
from xgboost import XGBClassifier

In [171]:
xgb=XGBClassifier(random_state=45,learning_rate=0.6,max_depth=9,colsample_bytree=1)
xgb.fit(x_train,y_train)
predxgb=xgb.predict(x_test)
print('Accuracy score is\n :',accuracy_score(y_test,predxgb))
print('\nConfusion matirx is :\n',confusion_matrix(y_test,predxgb))
print('\nClassification report is :',classification_report(y_test,predxgb))


Accuracy score is
 : 0.8913043478260869

Confusion matirx is :
 [[24  0]
 [ 5 17]]

Classification report is :               precision    recall  f1-score   support

           0       0.83      1.00      0.91        24
           1       1.00      0.77      0.87        22

    accuracy                           0.89        46
   macro avg       0.91      0.89      0.89        46
weighted avg       0.91      0.89      0.89        46

